name: cgp-meshcnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py36h1d69622_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py36h5fab9bb_1
  - cffi=1.14.0=py36h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py36_0
  - cython=0.27.3=py36h1860423_0
  - dataclasses=0.7=py36_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - intel-openmp=2019.4=243
  - ipydatawidgets=4.1.0=pyh9f0ad1d_0
  - ipykernel=5.4.2=py36he448a4c_0
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py36h5fab9bb_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.0=py36h2531618_0
  - lcms2=2.11=h396b838_0
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py36he6145b8_2
  - matplotlib=3.0.3=py36h5429711_0
  - meshplot=0.4.0=pyh9f0ad1d_1
  - mistune=0.8.4=py36h1d69622_1002
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36h5fab9bb_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.1=py36hfd86e86_0
  - notebook=6.1.5=py36h5fab9bb_0
  - numpy=1.19.4=py36h8732dcd_1
  - olefile=0.46=py36_0
  - openmesh-python=1.1.3=py36hc8e3772_0
  - openssl=1.1.1i=h27cfd23_0
  - pandoc=2.11.2=h36c2ea0_0
  - pandocfilters=1.4.2=py_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.2.4=py36h06a4308_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_2
  - pygments=2.7.3=pyhd8ed1ab_0
  - pymesh2=0.3=py36h9f0ad1d_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h1d69622_1
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pythreejs=2.2.1=pyh9f0ad1d_0
  - pytorch=1.7.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py36h7b6447c_1
  - pyzmq=20.0.0=py36h2b1bd32_1
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.5.3=py36h976291a_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.1=py36h06a4308_1
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2020.3=hfd86e86_0
  - tbb4py=2020.3=py36hfd86e86_0
  - terminado=0.9.1=py36h5fab9bb_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.0=py36
  - torchvision=0.8.1=py36_cu101
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36h5fab9bb_4
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - atomicwrites==1.4.0
    - calmsize==0.1.3
    - future==0.18.2
    - importlib-metadata==2.0.0
    - more-itertools==8.6.0
    - packaging==20.4
    - pandas==1.1.5
    - pluggy==0.13.1
    - protobuf==3.14.0
    - py==1.9.0
    - pytest==5.1.1
    - pytorch-memlab==0.2.3
    - tensorboardx==2.1
prefix: /home/andres/miniconda3/envs/cgp-meshcnn
